### ISSUE TITLE
Missing train_finqa.py file required for dev_train_beam target in Makefile

### ISSUE THREAD

**Issue by bardbardd0lm55** [iusztinpaul/hands-on-llms#33]
## Description

I am trying to execute the `dev_train_beam` target from the `Makefile`, but it seems like the `train_finqa.py` file, which is supposed to be located in the `./tools` directory, is missing from the repository.

## Steps to Reproduce

1. Navigate to the `training_pipeline` directory.
2. Run the command `make dev_train_beam`.

## Expected Behavior

The `make dev_train_beam` command should execute successfully by running the Beam training pipeline using the `train_finqa.py` script.

## Actual Behavior

An error is thrown indicating that the `train_finqa.py` file is not found:

## Additional Information

- I have searched through the repository to find the `train_finqa.py` file but was unable to locate it.
- There is no documentation explaining the absence of the `train_finqa.py` file or how to generate or locate it.

## Questions

- Should the `train_finqa.py` file be included in the repository?
- Are there any steps or commands that need to be executed to generate or locate the `train_finqa.py` file?
- Is there any additional documentation available that explains how to set up and execute the `dev_train_beam` target?

Thank you for your assistance!

**Comment by iusztinpaul** [comment]
Hello,

Just change it with train_run.py. We changed the file name and forgot to update all Makefile commands.

Thanks for letting us know.

**Comment by iusztinpaul** [comment]
I fixed this in this PR: https://github.com/iusztinpaul/hands-on-llms/pull/34

It is not merged as it is still a WIP, but you can take a look and inspire.

**Comment by bardbardd0lm55** [comment]
I feel dumb, it was that simple, i should've look more carefully, thank you so much! next time i will come up with something better. I love the work you guys have done. thanks again.

**Comment by bardbardd0lm55** [comment]
I feel dumb, it was that simple, i should've look more carefully, thank you so much! next time i will come up with something better. I love the work you guys have done. thanks again.

**Comment by iusztinpaul** [comment]
@bardbardd0lm55 No worries, it happens.

I am happy you take our course 🔥

**Comment by MotiBaadror** [comment]
I am facing one issue, make dev_train_beam , copying whole environment and taking too much time
