### ISSUE TITLE
Using fine-tuned model for inference

### ISSUE THREAD

**Issue by dvquy13** [iusztinpaul/hands-on-llms#74]
Hi @iusztinpaul,

Love the course so far!

I have a question: Shouldn't us use our fine-tuned model for inferenced instead of using Paul's peft model here?
https://github.com/iusztinpaul/hands-on-llms/blob/5c1887b4872df749e8863d2fb85f2f456b6af9ac/modules/training_pipeline/configs/dev_inference_config.yaml#L2

If yes then how should we publish our model from experiment to Comet Model Registry? Is it done manually via the `Register Model` button in the Comet experiment console view?
<img width="403" alt="image" src="https://github.com/iusztinpaul/hands-on-llms/assets/17514523/223a8629-88f1-4a62-86c1-bcc13070eee2">

Thanks!

**Comment by iusztinpaul** [comment]
Hello,

Happy to hear that!

Yes, you got that right! I added my own version to help you test things out, but ideally, you should use your own version.

You should pick the fine-tuned model and register it manually, as you suggested in the SS.

Just be careful to add a `name` and `version` that make sense and change them in the `yaml` file. When using your own fine-tuned model, it will be something like:
`yourname/your-model-name:your-version`

**Comment by dvquy13** [comment]
Got it working.
